### PR TITLE
feat: added basic layout

### PR DESCRIPTION
**Pull request by Enubia**

### CODE REVIEW

**Comment by Jacobjeevan** [comment]
nice :+1: We could classes for nav items into a const/function, right? Easy to change styles for all nav links at once.

Also for pages, how about wrapping page content in a Layout component, rather than having to import header + footer in every page? Layout can render header, child component and footer. That way we can make site wide layout changes at once.

(Not sure if either is a bad idea, that's what I usually do, but I don't have other frontend devs to criticize/help me improve on that area lol).

**Comment by Enubia** [comment]
this first markup is not responsive at all, @Jacobjeevan @stacysealky please fix :D

image

**Comment by Enubia** [comment]
navbar and breadcrumbs are configurable via navBar.ts and breadcrumbs in the footer template

**Comment by Enubia** [comment]
i also added all assets from the old frontend so that we can use it right away

**Comment by Jacobjeevan** [comment]
> this first markup is not responsive at all, @Jacobjeevan @stacysealky please fix :D
> 
> image

Added #12 for nav/footer :+1: :D

**Review by Jacobjeevan — APPROVED** [review]
:+1:

**Pull request merged**
